#!/usr/bin/env python3
"""
Ren'Py Translator - Writer Module
Scrive i file di traduzione in game/tl/<lang>/
"""

from __future__ import annotations
from pathlib import Path
import re

_RE_ESCAPE = re.compile(r'([\\"])')
_RE_HEX = re.compile(r"^#?[0-9a-fA-F]{3,8}$")


def _esc(s: str) -> str:
    return _RE_ESCAPE.sub(r"\\\1", s)


def write_activator(game_dir: Path, lang_code: str, splash_src: Path | None = None) -> Path:
    """
    Genera game/renpy_translator_<lang_code>.rpy — imposta la lingua di default,
    aggiunge hook runtime replace_text / say_menu_text_filter e, se splash_src
    è fornito, copia splash.png nella cartella game e aggiunge uno splash screen
    al primo avvio tramite label before_main_menu.
    """
    out = game_dir / f"renpy_translator_{lang_code}.rpy"

    splash_block = ""
    if splash_src and splash_src.exists():
        dest = game_dir / "renpy_translator_splash.png"
        import shutil
        shutil.copy2(splash_src, dest)
        splash_block = '''
image _rpt_splash = "renpy_translator_splash.png"

label before_main_menu:
    if persistent._rpt_splash_shown:
        return
    scene black
    with Pause(0.5)
    show _rpt_splash at truecenter
    with dissolve
    pause 2.5
    hide _rpt_splash
    with dissolve
    scene black
    with Pause(0.3)
    $ persistent._rpt_splash_shown = True
    return
'''
    content = f'''\
# -*- coding: utf-8 -*-
# Auto-generated by Ren\'Py Translator — DO NOT EDIT BY HAND
init python:
    config.default_language = "{lang_code}"
    try:
        if _preferences.language is None:
            config.language = "{lang_code}"
    except Exception:
        pass

init 9999 python:
    import re as _rpt_re

    _rpt_lang = "{lang_code}"
    _rpt_dict = {{}}
    try:
        _stl = renpy.game.script.translator.strings.get(_rpt_lang)
        if _stl and hasattr(_stl, "translations"):
            _rpt_dict = _stl.translations
    except Exception:
        pass

    _rpt_tag_re = _rpt_re.compile(r"\\{{[^}}]*}}")
    def _rpt_strip_tags(s):
        return _rpt_tag_re.sub("", s)

    def _rpt_lookup(s):
        if not s:
            return None
        r = _rpt_dict.get(s)
        if r is not None:
            return r
        # fallback: senza tag Ren\'Py
        if "{{" in s:
            t = _rpt_strip_tags(s).strip()
            if t and t != s:
                r = _rpt_dict.get(t)
                if r is not None:
                    return r
        return None

    _rpt_old_replace = getattr(config, "replace_text", None)
    if not getattr(_rpt_old_replace, "_is_rpt", False):
        def _rpt_replace_text(s):
            hit = _rpt_lookup(s)
            if hit is not None:
                return (_rpt_old_replace(hit) if _rpt_old_replace else hit)
            return (_rpt_old_replace(s) if _rpt_old_replace else s)
        _rpt_replace_text._is_rpt = True
        config.replace_text = _rpt_replace_text

    _rpt_old_menu = getattr(config, "say_menu_text_filter", None)
    if not getattr(_rpt_old_menu, "_is_rpt", False):
        def _rpt_menu_filter(s):
            hit = _rpt_lookup(s)
            if hit is not None:
                return hit
            return (_rpt_old_menu(s) if _rpt_old_menu else s)
        _rpt_menu_filter._is_rpt = True
        config.say_menu_text_filter = _rpt_menu_filter
{splash_block}'''
    out.write_text(content, encoding="utf-8")
    return out


def write_tl_files(
    game_dir: Path,
    lang_code: str,
    items: list,
    translations: dict[str, str],
) -> list[Path]:
    """
    Scrive i file di traduzione in game/tl/<lang_code>/.
    - Menu: formato nativo  translate <lang> <id>:\n    "testo tradotto"
    - Dialoghi/UI: formato  translate <lang> strings:\n    old "..."\n    new "..."
    """
    tl_dir = game_dir / "tl" / lang_code
    if tl_dir.exists():
        for f in tl_dir.glob("*.rpy"):
            f.unlink()
    tl_dir.mkdir(parents=True, exist_ok=True)

    # Raggruppa per file sorgente
    groups: dict[str, list] = {}
    for item in items:
        if item.text in translations and translations[item.text]:
            groups.setdefault(item.file, []).append(item)

    seen_strings: set[str] = set()
    seen_menu: set[str] = set()
    menu_counter = [0]
    written = []

    for file_key, file_items in groups.items():
        filename = file_key.replace("game/", "").replace("/", "_")
        if not filename.endswith(".rpy"):
            filename += ".rpy"
        out = tl_dir / filename

        lines = ["# Auto-generated by Ren'Py Translator — DO NOT EDIT BY HAND"]
        had_content = False

        # ── FASE 1: menu nel formato nativo translate <lang> <id>: ──────────
        menu_items = [i for i in file_items if i.kind == "menu"]
        if menu_items:
            lines.append("")
        for item in menu_items:
            old = item.text.strip()
            new = translations.get(item.text, "").strip()
            if not old or not new or old in seen_menu:
                continue
            seen_menu.add(old)
            mid = f"rpt_menu_{menu_counter[0]}"
            menu_counter[0] += 1
            lines.append(f"# {item.file}:{item.line}")
            lines.append(f"translate {lang_code} {mid}:")
            lines.append("")
            lines.append(f'    # "{_esc(old)}"')
            lines.append(f'    "{_esc(new)}"')
            lines.append("")
            had_content = True

        # ── FASE 2: dialoghi/narrazione/ui nel formato old/new strings ───────
        str_items = [i for i in file_items if i.kind != "menu"]
        if str_items:
            str_lines = []
            for item in str_items:
                old = item.text.strip()
                new = translations.get(item.text, "").strip()
                if not old or not new:
                    continue
                if _RE_HEX.match(old) or old in seen_strings:
                    continue
                seen_strings.add(old)
                str_lines.append(f"    # {item.file}:{item.line}")
                str_lines.append(f'    old "{_esc(old)}"')
                str_lines.append(f'    new "{_esc(new)}"')
                str_lines.append("")
            if str_lines:
                lines.append("")
                lines.append(f"translate {lang_code} strings:")
                lines.append("")
                lines.extend(str_lines)
                had_content = True

        if had_content:
            out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
            written.append(out)

    return written
