#!/usr/bin/env python3
"""
Ren'Py Translator - Writer Module
Scrive i file di traduzione in game/tl/<lang>/
"""

from __future__ import annotations
from pathlib import Path
import re
import shutil

_RE_ESCAPE = re.compile(r'([\\"])')
_RE_HEX = re.compile(r"^#?[0-9a-fA-F]{3,8}$")


def _esc(s: str) -> str:
    s = _RE_ESCAPE.sub(r"\\\1", s)
    return s.replace("\n", "\\n").replace("\r", "").replace("\t", "\\t")


ORIGINAL_BACKUP_NAME = "tl_bak_original"


def _tl_dir(game_dir: Path, lang_code: str) -> Path:
    return game_dir / "tl" / lang_code


_BACKUPS_DIR = "renpy_translator_backups"


def _original_backup_dir(game_dir: Path) -> Path:
    return game_dir.parent / _BACKUPS_DIR / ORIGINAL_BACKUP_NAME


def _legacy_backups(game_dir: Path) -> list[Path]:
    legacy_dir = game_dir.parent / _BACKUPS_DIR
    old = [p for p in game_dir.glob("tl_bak_*") if p.is_dir() and p.name != ORIGINAL_BACKUP_NAME]
    new = [p for p in legacy_dir.glob("tl_bak_*") if p.is_dir() and p.name != ORIGINAL_BACKUP_NAME]
    return sorted(old + new, key=lambda p: p.stat().st_mtime)


def _original_backup(game_dir: Path) -> Path | None:
    original = _original_backup_dir(game_dir)
    # Se il backup originale era dentro game/, spostalo fuori per non farlo caricare a Ren'Py
    old_original = game_dir / ORIGINAL_BACKUP_NAME
    if old_original.exists() and not original.exists():
        original.parent.mkdir(parents=True, exist_ok=True)
        old_original.rename(original)
    if original.is_dir():
        return original
    backups = _legacy_backups(game_dir)
    if not backups:
        return None
    original.parent.mkdir(parents=True, exist_ok=True)
    backups[0].rename(original)
    for backup in backups[1:]:
        shutil.rmtree(backup)
    return original


def backup_tl_dir(game_dir: Path, lang_code: str) -> Path | None:
    """
    Crea un backup unico e originale della cartella game/tl/<lang_code>/ e del
    file renpy_translator_<lang_code>.rpy se non esiste già.
    """
    tl_dir = _tl_dir(game_dir, lang_code)
    activator = game_dir / f"renpy_translator_{lang_code}.rpy"

    original = _original_backup(game_dir)
    if original is None:
        # Elimina eventuali backup legacy spuri
        for backup in _legacy_backups(game_dir):
            shutil.rmtree(backup)
        # Se non c'è nulla da backuppare, non creare un backup vuoto
        if not tl_dir.exists() and not activator.exists():
            return None
        original = _original_backup_dir(game_dir)
        original.mkdir(parents=True, exist_ok=True)
        if tl_dir.exists():
            shutil.copytree(tl_dir, original / "tl" / lang_code)
        if activator.exists():
            shutil.copy2(activator, original / f"renpy_translator_{lang_code}.rpy")
    return original


def restore_tl_backup(game_dir: Path, lang_code: str) -> Path | None:
    """Ripristina il backup originale della traduzione."""
    original = _original_backup(game_dir)
    if original is None:
        return None
    tl_dir = _tl_dir(game_dir, lang_code)
    activator = game_dir / f"renpy_translator_{lang_code}.rpy"
    if tl_dir.exists():
        shutil.rmtree(tl_dir)
    backup_tl = original / "tl" / lang_code
    if backup_tl.exists():
        shutil.copytree(backup_tl, tl_dir)
    backup_activator = original / f"renpy_translator_{lang_code}.rpy"
    if backup_activator.exists():
        shutil.copy2(backup_activator, activator)
    elif activator.exists():
        activator.unlink()
    return original


def write_activator(game_dir: Path, lang_code: str, splash_src: Path | None = None) -> Path:
    """
    Genera game/renpy_translator_<lang_code>.rpy — imposta la lingua di default,
    aggiunge hook runtime replace_text / say_menu_text_filter e, se splash_src
    è fornito, copia splash.png nella cartella game e aggiunge uno splash screen
    al primo avvio tramite label before_main_menu.
    """
    out = game_dir / f"renpy_translator_{lang_code}.rpy"

    splash_block = ""
    if splash_src and splash_src.exists():
        dest = game_dir / "renpy_translator_splash.png"
        import shutil
        shutil.copy2(splash_src, dest)
        splash_block = '''
image _rpt_splash = "renpy_translator_splash.png"

label before_main_menu:
    if renpy.session.get("_rpt_splash_shown"):
        return
    $ renpy.session["_rpt_splash_shown"] = True
    scene black
    with Pause(0.5)
    show _rpt_splash at truecenter
    with dissolve
    pause 2.5
    hide _rpt_splash
    with dissolve
    scene black
    with Pause(0.3)
    return
'''
    content = f'''\
# -*- coding: utf-8 -*-
# Auto-generated by Ren\'Py Translator — DO NOT EDIT BY HAND
init python:
    config.default_language = "{lang_code}"
    try:
        if _preferences.language is None:
            config.language = "{lang_code}"
    except Exception:
        pass

init 9999 python:
    import re as _rpt_re

    _rpt_lang = "{lang_code}"
    _rpt_dict = {{}}
    try:
        _stl = renpy.game.script.translator.strings.get(_rpt_lang)
        if _stl and hasattr(_stl, "translations"):
            _rpt_dict = _stl.translations
    except Exception:
        pass

    _rpt_tag_re = _rpt_re.compile(r"\\{{[^}}]*}}")
    def _rpt_strip_tags(s):
        return _rpt_tag_re.sub("", s)

    def _rpt_lookup(s):
        if not s:
            return None
        r = _rpt_dict.get(s)
        if r is not None:
            return r
        # fallback: senza tag Ren\'Py
        if "{{" in s:
            t = _rpt_strip_tags(s).strip()
            if t and t != s:
                r = _rpt_dict.get(t)
                if r is not None:
                    return r
        return None

    _rpt_old_replace = getattr(config, "replace_text", None)
    if not getattr(_rpt_old_replace, "_is_rpt", False):
        def _rpt_replace_text(s):
            hit = _rpt_lookup(s)
            if hit is not None:
                return (_rpt_old_replace(hit) if _rpt_old_replace else hit)
            return (_rpt_old_replace(s) if _rpt_old_replace else s)
        _rpt_replace_text._is_rpt = True
        config.replace_text = _rpt_replace_text

{splash_block}'''
    out.write_text(content, encoding="utf-8")
    return out


def write_runtime_filter(tl_dir: Path, lang_code: str) -> None:
    """
    Scrive tl/<lang>/zz_runtime_filter.rpy — caricato automaticamente da Ren'Py
    quando la lingua e' attiva. Legge le traduzioni da _rpt_dict (popolato dai
    translate strings: nei file TL) e le applica via say_menu_text_filter.
    Nessun file JSON esterno — stesso approccio di UltraRenpyTranslator.
    """
    rpy = f'''# Auto-generated by Ren\'Py Translator \u2014 DO NOT EDIT BY HAND
# Runtime menu filter (language: {lang_code})
# Caricato automaticamente da Ren\'Py quando la lingua e\' attiva.

init 9999 python:
    import re as _rpt_re

    _rpt_lang = "{lang_code}"
    _rpt_dict = {{}}
    try:
        _stl = renpy.game.script.translator.strings.get(_rpt_lang)
        if _stl and hasattr(_stl, "translations"):
            _rpt_dict = _stl.translations
    except Exception:
        pass

    _rpt_tag_re = _rpt_re.compile(r"\\{{[^}}]*}}")

    def _rpt_normalize(s):
        s = s.replace("\\u2018", "'").replace("\\u2019", "'")
        s = s.replace("\\u201c", '"').replace("\\u201d", '"')
        s = s.replace("\\u2026", "...").replace("\\u2014", "--").replace("\\u2013", "-")
        return _rpt_re.sub(r"[ \\n]+", " ", s).strip()

    def _rpt_menu_filter(s):
        if not s:
            return s
        try:
            r = _rpt_dict.get(s)
            if r is not None:
                return r
            n = _rpt_normalize(s)
            if n != s:
                r = _rpt_dict.get(n)
                if r is not None:
                    return r
            stripped = _rpt_tag_re.sub("", s).strip()
            if stripped and stripped != s:
                r = _rpt_dict.get(stripped)
                if r is not None:
                    return r
        except Exception:
            pass
        return s

    _rpt_menu_filter._is_rpt = True
    if not getattr(config.say_menu_text_filter, "_is_rpt", False):
        config.say_menu_text_filter = _rpt_menu_filter
'''
    (tl_dir / "zz_runtime_filter.rpy").write_text(rpy, encoding="utf-8")


_WT_PH_RE = re.compile(r'\[r_[A-Za-z_]\w*\]')


def _wt_segments(text: str) -> list[str]:
    """Restituisce i segmenti di testo tra i placeholder [r_*]."""
    return [s for s in _WT_PH_RE.split(text) if s]


def write_runtime_wt_replace(
    tl_dir: Path,
    lang_code: str,
    items: list,
    translations: dict[str, str],
) -> None:
    """
    Scrive tl/<lang>/zz_runtime_replace.rpy con config.replace_text per
    tradurre a runtime le scelte del WT Mod senza alterare i placeholder colori.
    """
    wt_file = "walkthrough_mod_0_9_0.rpy"
    replacements: dict[str, str] = {}
    for item in items:
        if getattr(item, "kind", None) != "choice" or getattr(item, "file", "") != wt_file:
            continue
        old = item.text.strip()
        new = translations.get(old, "").strip()
        if not old or not new:
            continue
        old_segs = _wt_segments(old)
        new_segs = _wt_segments(new)
        if len(old_segs) != len(new_segs):
            continue
        for o, n in zip(old_segs, new_segs):
            if o and o != n and not _RE_HEX.match(o):
                replacements[o] = n
    if not replacements:
        return
    # Sostituire prima le stringhe più lunghe per evitare match parziali
    sorted_pairs = sorted(replacements.items(), key=lambda kv: -len(kv[0]))
    pairs = ",\n        ".join(
        f'"{_esc(o)}": "{_esc(n)}"' for o, n in sorted_pairs
    )
    rpy = f'''# Auto-generated by Ren\'Py Translator \u2014 DO NOT EDIT BY HAND
# Runtime WT Mod text replacement (language: {lang_code})

init 9999 python:
    _wt_replacements = {{
        {pairs}
    }}

    _wt_old_replace = config.replace_text
    def _wt_replace_text(text):
        if text and "[r_" in text:
            for _wt_old, _wt_new in _wt_replacements.items():
                text = text.replace(_wt_old, _wt_new)
        if _wt_old_replace is not None:
            return _wt_old_replace(text)
        return text

    config.replace_text = _wt_replace_text
'''
    (tl_dir / "zz_runtime_replace.rpy").write_text(rpy, encoding="utf-8")


def write_tl_files(
    game_dir: Path,
    lang_code: str,
    items: list,
    translations: dict[str, str],
) -> list[Path]:
    """
    Scrive i file di traduzione in game/tl/<lang_code>/.
    - Menu: formato nativo  translate <lang> <id>:\n    "testo tradotto"
    - Dialoghi/UI: formato  translate <lang> strings:\n    old "..."\n    new "..."
    """
    tl_dir = game_dir / "tl" / lang_code
    if tl_dir.exists():
        for f in tl_dir.glob("*.rpy"):
            f.unlink()
    tl_dir.mkdir(parents=True, exist_ok=True)

    # Raggruppa per file sorgente
    groups: dict[str, list] = {}
    for item in items:
        if item.text in translations and translations[item.text]:
            groups.setdefault(item.file, []).append(item)

    seen: set[str] = set()
    written = []

    for file_key, file_items in groups.items():
        filename = file_key.replace("game/", "").replace("/", "_")
        if not filename.endswith(".rpy"):
            filename += ".rpy"
        out = tl_dir / filename

        str_lines = []
        for item in file_items:
            old = item.text.strip()
            new = translations.get(item.text, "").strip()
            if not old or not new or _RE_HEX.match(old) or old in seen:
                continue
            seen.add(old)
            str_lines.append(f"    # {item.file}:{item.line}")
            str_lines.append(f'    old "{_esc(old)}"')
            str_lines.append(f'    new "{_esc(new)}"')
            str_lines.append("")

        if str_lines:
            lines = [
                "# Auto-generated by Ren'Py Translator \u2014 DO NOT EDIT BY HAND",
                f"translate {lang_code} strings:",
                "",
            ]
            lines.extend(str_lines)
            out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
            written.append(out)

    write_runtime_filter(tl_dir, lang_code)
    write_runtime_wt_replace(tl_dir, lang_code, items, translations)
    return written
