#!/usr/bin/env python3
"""
Ren'Py Translator - Writer Module
Scrive i file di traduzione in game/tl/<lang>/
"""

from __future__ import annotations
from pathlib import Path
import re
import json

_RE_ESCAPE = re.compile(r'([\\"])')
_RE_HEX = re.compile(r"^#?[0-9a-fA-F]{3,8}$")


def _esc(s: str) -> str:
    return _RE_ESCAPE.sub(r"\\\1", s)


def write_activator(game_dir: Path, lang_code: str, splash_src: Path | None = None) -> Path:
    """
    Genera game/renpy_translator_<lang_code>.rpy — imposta la lingua di default,
    aggiunge hook runtime replace_text / say_menu_text_filter e, se splash_src
    è fornito, copia splash.png nella cartella game e aggiunge uno splash screen
    al primo avvio tramite label before_main_menu.
    """
    out = game_dir / f"renpy_translator_{lang_code}.rpy"

    splash_block = ""
    if splash_src and splash_src.exists():
        dest = game_dir / "renpy_translator_splash.png"
        import shutil
        shutil.copy2(splash_src, dest)
        splash_block = '''
image _rpt_splash = "renpy_translator_splash.png"

label before_main_menu:
    scene black
    with Pause(0.5)
    show _rpt_splash at truecenter
    with dissolve
    pause 2.5
    hide _rpt_splash
    with dissolve
    scene black
    with Pause(0.3)
    return
'''
    content = f'''\
# -*- coding: utf-8 -*-
# Auto-generated by Ren\'Py Translator — DO NOT EDIT BY HAND
init python:
    config.default_language = "{lang_code}"
    try:
        if _preferences.language is None:
            config.language = "{lang_code}"
    except Exception:
        pass

init 9999 python:
    import re as _rpt_re

    _rpt_lang = "{lang_code}"
    _rpt_dict = {{}}
    try:
        _stl = renpy.game.script.translator.strings.get(_rpt_lang)
        if _stl and hasattr(_stl, "translations"):
            _rpt_dict = _stl.translations
    except Exception:
        pass

    _rpt_tag_re = _rpt_re.compile(r"\\{{[^}}]*}}")
    def _rpt_strip_tags(s):
        return _rpt_tag_re.sub("", s)

    def _rpt_lookup(s):
        if not s:
            return None
        r = _rpt_dict.get(s)
        if r is not None:
            return r
        # fallback: senza tag Ren\'Py
        if "{{" in s:
            t = _rpt_strip_tags(s).strip()
            if t and t != s:
                r = _rpt_dict.get(t)
                if r is not None:
                    return r
        return None

    _rpt_old_replace = getattr(config, "replace_text", None)
    if not getattr(_rpt_old_replace, "_is_rpt", False):
        def _rpt_replace_text(s):
            hit = _rpt_lookup(s)
            if hit is not None:
                return (_rpt_old_replace(hit) if _rpt_old_replace else hit)
            return (_rpt_old_replace(s) if _rpt_old_replace else s)
        _rpt_replace_text._is_rpt = True
        config.replace_text = _rpt_replace_text

{splash_block}'''
    out.write_text(content, encoding="utf-8")
    return out


def write_runtime_filter(tl_dir: Path, lang_code: str, translations: dict[str, str]) -> None:
    """
    Scrive in tl/<lang>/:
      - rt_map.json           : {originale: tradotto}
      - zz_runtime_filter.rpy : caricato auto da Ren'Py, imposta say_menu_text_filter
    """
    clean = {k: v for k, v in translations.items() if k and v}
    (tl_dir / "rt_map.json").write_text(
        json.dumps(clean, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    rpy = f'''# Auto-generated by Ren\'Py Translator — DO NOT EDIT BY HAND
# Runtime translation filter (language: {lang_code})

init -2 python:
    import json as _rt_json

    _RT_MAP = {{}}
    try:
        import renpy as _rt_renpy
        _p = _rt_renpy.loader.transfn("tl/{lang_code}/rt_map.json")
        with open(_p, "r", encoding="utf-8") as _f:
            _RT_MAP = _rt_json.load(_f)
    except Exception:
        pass

    def _rt_filter(s):
        try:
            return _RT_MAP.get(s, s)
        except Exception:
            return s

define config.say_menu_text_filter = _rt_filter
'''
    (tl_dir / "zz_runtime_filter.rpy").write_text(rpy, encoding="utf-8")


def write_tl_files(
    game_dir: Path,
    lang_code: str,
    items: list,
    translations: dict[str, str],
) -> list[Path]:
    """
    Scrive i file di traduzione in game/tl/<lang_code>/.
    - Menu: formato nativo  translate <lang> <id>:\n    "testo tradotto"
    - Dialoghi/UI: formato  translate <lang> strings:\n    old "..."\n    new "..."
    """
    tl_dir = game_dir / "tl" / lang_code
    if tl_dir.exists():
        for f in tl_dir.glob("*.rpy"):
            f.unlink()
    tl_dir.mkdir(parents=True, exist_ok=True)

    # Raggruppa per file sorgente
    groups: dict[str, list] = {}
    for item in items:
        if item.text in translations and translations[item.text]:
            groups.setdefault(item.file, []).append(item)

    seen: set[str] = set()
    written = []

    for file_key, file_items in groups.items():
        filename = file_key.replace("game/", "").replace("/", "_")
        if not filename.endswith(".rpy"):
            filename += ".rpy"
        out = tl_dir / filename

        str_lines = []
        for item in file_items:
            old = item.text.strip()
            new = translations.get(item.text, "").strip()
            if not old or not new or _RE_HEX.match(old) or old in seen:
                continue
            seen.add(old)
            str_lines.append(f"    # {item.file}:{item.line}")
            str_lines.append(f'    old "{_esc(old)}"')
            str_lines.append(f'    new "{_esc(new)}"')
            str_lines.append("")

        if str_lines:
            lines = [
                "# Auto-generated by Ren'Py Translator \u2014 DO NOT EDIT BY HAND",
                f"translate {lang_code} strings:",
                "",
            ]
            lines.extend(str_lines)
            out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
            written.append(out)

    write_runtime_filter(tl_dir, lang_code, translations)
    return written
